---
driver:
  name: ec2
  require_chef_omnibus: true
  ssh_timeout: 20
  ssh_retries: 5
  iam_profile_name: TestKitchenRole
 
platforms:
  - name: ubuntu-14.04
    driver:
      username: ubuntu
      tags:
        Name: optoro_zookeeper-test_kitchen
 
provisioner:
  name: chef_zero
  require_chef_omnibus:  11.16.4
  ebs_delete_on_termination: true
 
suites:
- name: default
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[apt]
    - recipe[optoro_zookeeper::default]
  attributes:
    apt: 
      compiletime: true

